/// Flutter icons SecompSocial
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SecompSocial
///      fonts:
///       - asset: fonts/SecompSocial.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SecompSocial {
  SecompSocial._();

  static const _kFontFam = 'SecompSocial';

  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
}
